// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF34YnulJVoKmsz7MgdnGhwiG9twx2uAU',
    appId: '1:1069623034484:web:9c3da4a5fb5cea9cb40721',
    messagingSenderId: '1069623034484',
    projectId: 'evently-b03ff',
    authDomain: 'evently-b03ff.firebaseapp.com',
    storageBucket: 'evently-b03ff.firebasestorage.app',
    measurementId: 'G-9RM02PRDTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzqYAVvg7EKuerNKFGkmuvEvyWXO_sXGE',
    appId: '1:1069623034484:android:7f3a34154313f8d3b40721',
    messagingSenderId: '1069623034484',
    projectId: 'evently-b03ff',
    storageBucket: 'evently-b03ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAzXqMxtoesWY6-kCcf_s3LOtiLmUQ1Yk',
    appId: '1:1069623034484:ios:849e19eea5a2f024b40721',
    messagingSenderId: '1069623034484',
    projectId: 'evently-b03ff',
    storageBucket: 'evently-b03ff.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAzXqMxtoesWY6-kCcf_s3LOtiLmUQ1Yk',
    appId: '1:1069623034484:ios:849e19eea5a2f024b40721',
    messagingSenderId: '1069623034484',
    projectId: 'evently-b03ff',
    storageBucket: 'evently-b03ff.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF34YnulJVoKmsz7MgdnGhwiG9twx2uAU',
    appId: '1:1069623034484:web:d16701504981b6d1b40721',
    messagingSenderId: '1069623034484',
    projectId: 'evently-b03ff',
    authDomain: 'evently-b03ff.firebaseapp.com',
    storageBucket: 'evently-b03ff.firebasestorage.app',
    measurementId: 'G-6184RWVCSR',
  );
}
